name: Build library

on:
  push:

  repository_dispatch:
    types: [new_php_lib_event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # OS additions
      - name: Add to OS
        run: |
           sudo apt-get install memcached
           #sudo systemctl status memcached
           
      # Checkout our code 
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.2
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
            coverage: xdebug

      # Validate the Composer files
      - name: Validate composer.json and composer.lock
        run: composer validate

      # Fetch the vendor folder from the cache, keyed off the composer.lock file 
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Run composer install if the vendor folder wasn't cached (based on the current composer.lock file) 
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      # install NPM dependencies
      - name: Install NPM dependencies
        run: npm install

      # Rev the version number for the next build
      - name: Rev Version
        id: rev-version
        run: |
          npm --no-git-tag-version version patch
          echo "project_name=$(sed -n -e 's/.*"name": "\(.*\)",.*/\1/p' <<< cat package.json)" >> $GITHUB_OUTPUT
          echo "project_version=$(sed -n -e 's/.*"version": "\(.*\)",.*/\1/p' <<< cat package.json)" >> $GITHUB_OUTPUT

      # build the app
      - name: Build
        run: |
          npm run build
          mv ${{ steps.rev-version.outputs.project_name }}.zip ${{ steps.rev-version.outputs.project_name }}-${{ steps.rev-version.outputs.project_version }}.zip
          
      - name: Configure Git user
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
        
      # Save versioned files 
      - name: Commit version files
        id: commit-version
        run: |
          git add package.json package-lock.json composer.json composer.lock
          echo -n "Rev to version ${{ steps.rev-version.outputs.project_version }}" | git commit -F -
          git push
          echo "version-commit-ref=$(git show-ref --heads -s)" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.rev-version.outputs.project_version }}
          name: Release ${{ steps.rev-version.outputs.project_version }}
          commit: ${{ steps.commit-version.outputs.commit-ref }}
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts:
            ${{ steps.rev-version.outputs.project_name }}-${{ steps.rev-version.outputs.project_version }}.zip
